name: CI

on: 
 repository_dispatch:
 push:
    paths-ignore:
      - README.md

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup tmate session
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H%M')"
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml -Dtimestamp=${{steps.date.outputs.date}}
    - name: Create Release
      id: create_release
      if: github.event_name == 'push'
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{steps.date.outputs.date}}
        release_name: ${{steps.date.outputs.date}}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset 
      if: github.event_name == 'push'
      uses: actions/upload-release-asset@v1.0.1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/SedeveModules-${{steps.date.outputs.date}}.jar
        asset_name: SedeveModules-${{steps.date.outputs.date}}.jar
        asset_content_type: application/zip
    - name: Upload dateless Release Asset
      id: upload-dateless-release-asset 
      if: github.event_name == 'push'
      uses: actions/upload-release-asset@v1.0.1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/SedeveModules.jar
        asset_name: SedeveModules.jar
        asset_content_type: application/zip
    - name: Upload Release Asset
      id: upload-release-asset-deps
      if: github.event_name == 'push'
      uses: actions/upload-release-asset@v1.0.1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/SedeveModules-deps-${{steps.date.outputs.date}}.jar
        asset_name: SedeveModules-deps-${{steps.date.outputs.date}}.jar
        asset_content_type: application/zip
    - name: Upload dateless Release Asset
      id: upload-dateless-release-asset-deps
      if: github.event_name == 'push'
      uses: actions/upload-release-asset@v1.0.1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/SedeveModules-deps.jar
        asset_name: SedeveModules-deps.jar
        asset_content_type: application/zip
